### ISSUE TITLE
Angular 13: Unable to build Cannot find namespace 'TopoJSON'

### ISSUE THREAD

**Issue by AhmedHalat** [f5/unovis#79]
When trying to build a project with `ng serve` I get the following errors
```sh
Error: node_modules/@unovis/angular/dist/lib/components/topojson-map/topojson-map.component.d.ts:56:16 - error TS2503: Cannot find namespace 'TopoJSON'.

56     topojson?: TopoJSON.Topology;
                  ~~~~~~~~


Error: node_modules/@unovis/ts/components/topojson-map/config.d.ts:9:16 - error TS2503: Cannot find namespace 'TopoJSON'.

9     topojson?: TopoJSON.Topology;
                 ~~~~~~~~
```
I've added TopoJSON to my package.json but the issue persists. I've added the following packages:
```json
"@types/topojson-specification": "^1.0.2",
"topojson": "^3.0.2",
"topojson-client": "^3.1.0",
```
However, updating the types in the files to `Any` fixes the issue. Or just importing TopoJSON into the file explicitly. 
Is there something I'm missing in setting up the package? I figure that my tsconfig setup can also be the issue but just wanted to check if you guys have seen this before

\
Had one more error that was fixed by adding `@types/lodash`
```sh
Error: node_modules/@unovis/ts/core/component/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'lodash'.

1 /// <reference types="lodash" />
                        ~~~~~~
```

**Comment by rokotyan** [comment]
@AhmedHalat Thanks for reporting! 

Yes, we had issues with TopoJSON typings before but I thought we've solved those. I've found a few issues in the `package.json` file of `@unovis/ts`. Can you please try installing version `1.0.1-beta.0`:

```bash
npm i -P @unovis/ts@1.0.1-beta.0 --force
```

And post whether it helped or not?

**Comment by AhmedHalat** [comment]
@rokotyan Issue persists on `1.0.1-beta.0`. No changes

**Comment by rokotyan** [comment]
@AhmedHalat Ok, I'll need to look deeper into the issue. I'll keep you posted!

**Comment by rokotyan** [comment]
@AhmedHalat I've tried to set up a new Angular app with `ng new` and was able to catch and fix a bunch of types-related errors. However, the TopoJSON error was not there. So if you could share your tsconfig, that might be helpful.

In the meantime, can you please also try changing `@unovis/ts` and `@unovis/angular` versions to `1.0.1-beta.5` in your `package.json`, then remove `node_modules`, and  run `npm install`.

```bash
npm i -P @unovis/ts@1.0.1-beta.5 @unovis/angular@1.0.1-beta.5
rm -rf node_modules
npm i
```

**Comment by astefano** [comment]
Hello, 
Just to say that i followed the steps you suggested wrt `1.0.1-beta.5` and i still got the error with TopoJSON for which i applied the fix @AhmedHalat mentioned (the import). I also got some other errors regarding `export =` and i fixed these by adding 
```
"esModuleInterop": true,
"allowSyntheticDefaultImports": true
```
to `config.json` (as suggested at https://stackoverflow.com/questions/60935889/cant-do-a-default-import-in-angular-9).
With these, the basic app i wanted to try (basic-line-chart) now works.

**Comment by AhmedHalat** [comment]
Odd. Updating my tsconfig as @astefano and the new doc update @rokotyan made suggested, but it doesn't seem to fix it for me. I guess one of my other tsconfig settings might be causing the issue here?

Can we compare other versions or our tsconfig? node `v16.17.0`
```
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cdk                    13.1.1
@angular/cli                    13.1.4
@angular/material               13.1.1
@schematics/angular             13.1.4
rxjs                            6.6.7
typescript                      4.5.5
```

**Comment by rokotyan** [comment]
@AhmedHalat I've tried to create a new Angular app again with `ng new` on another machine, and the only change to tsconfig I needed to do to make it work was enabling `allowSyntheticDefaultImports`.

Here's how that `tsconfig.json` looks:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "useDefineForClassFields": false,
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
``` 

And `package.json`:
```json
{
  "name": "unovis-angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^15.0.0",
    "@angular/common": "^15.0.0",
    "@angular/compiler": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/router": "^15.0.0",
    "@unovis/angular": "^1.0.1-beta.5",
    "@unovis/ts": "^1.0.1-beta.5",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.4",
    "@angular/cli": "~15.0.4",
    "@angular/compiler-cli": "^15.0.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.8.2"
  }
}
```

My node version is `16.15.0`.

@AhmedHalat Can you please share your tsconfig too?

**Comment by AhmedHalat** [comment]
@rokotyan Finally managed to get it working. None of my `tsconfig.json` settings seemed to fix it (including adding `allowSyntheticDefaultImports`), but the following did.

I added `"@types/topojson-client"` to my dev dependencies and to my `types` in `compilerOptions` in `tsconfig.app.json`
```json
"compilerOptions": {
    "types": ["node", "...", "topojson-client"]
``` 

I also got off the beta and I'm still no longer getting the Namespace issue. 
Thanks a lot for all your help!

**Comment by AhmedHalat** [comment]
If you still want my `tsconfig`, here it is:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "noImplicitReturns": true,
    "preserveSymlinks": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2019", "dom"],
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": false,
    "fullTemplateTypeCheck": true
  }
}

```

**Comment by rokotyan** [comment]
@AhmedHalat Great and thanks for writing about your fix!

When you explicitly set `types` in your tsconfig, only those types will be visible to the compiler. That's why you had to add `"topojson-client"` there explicitly. Here is an excerpt from [TSConfig docs](https://www.typescriptlang.org/tsconfig#types):

>By default all visible ”@types” packages are included in your compilation. ...
> ...
> If types is specified, only packages listed will be included in the global scope.

We'll add a few words about it to our docs too.
